version: '3.7'
services:
  fozzie.example.com:
    build:
      context: ./node
    image: heckler-node:latest
    hostname: fozzie
    domainname: example.com
    # needed to avoid facter using dns search for fqdn
    dns_search: ""
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /run/lock
      - type: bind
        source: ../
        target: /heckler
    networks:
          heckler:
            ipv4_address: 172.18.0.2
  statler.example.com:
    build:
      context: ./node
    image: heckler-node:latest
    hostname: statler
    domainname: example.com
    # needed to avoid facter using dns search for fqdn
    dns_search: ""
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /run/lock
      - type: bind
        source: ../
        target: /heckler
    networks:
          heckler:
            ipv4_address: 172.18.0.3
  waldorf.example.com:
    build:
      context: ./node
    image: heckler-node:latest
    hostname: waldorf
    domainname: example.com
    # needed to avoid facter using dns search for fqdn
    dns_search: ""
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /run/lock
      - type: bind
        source: ../
        target: /heckler
    networks:
          heckler:
            ipv4_address: 172.18.0.4
  heckler.example.com:
    build:
      context: ./node
    image: heckler-node:latest
    hostname: heckler
    domainname: example.com
    # needed to avoid facter using dns search for fqdn
    dns_search: ""
    volumes:
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /run/lock
      - type: bind
        source: ../
        target: /heckler
    networks:
          heckler:
            ipv4_address: 172.18.0.5
networks:
  heckler:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/24"
